// Code generated by an5ORM. DO NOT EDIT.
package an5client

import (
	"time"
)

// EmbeddingConfig - Embedding provider configuration. Stores API keys and model settings for RAG features.
type EmbeddingConfig struct {
	Id string `json:"id" db:"id"`
	Provider string `json:"provider" db:"provider"`
	ApiKey string `json:"apiKey" db:"api_key"`
	Model *string `json:"model,omitempty" db:"model"`
	Endpoint *string `json:"endpoint,omitempty" db:"endpoint"`
	IsActive bool `json:"isActive" db:"is_active"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
	UpdatedAt time.Time `json:"updatedAt" db:"updated_at"`
}

// ─── EmbeddingConfig ORM Types ──────────────────────────────────────────────────────────

// EmbeddingConfigWhereInput provides type-safe filtering for EmbeddingConfig queries.
type EmbeddingConfigWhereInput struct {
	AND []EmbeddingConfigWhereInput
	OR  []EmbeddingConfigWhereInput
	NOT *EmbeddingConfigWhereInput
	Id *StringFilter
	Provider *StringFilter
	ApiKey *StringFilter
	Model *StringFilter
	Endpoint *StringFilter
	IsActive *BoolFilter
	CreatedAt *DateTimeFilter
	UpdatedAt *DateTimeFilter
}

// EmbeddingConfigOrderByInput provides type-safe ordering for EmbeddingConfig queries.
type EmbeddingConfigOrderByInput struct {
	Id *SortOrder
	Provider *SortOrder
	ApiKey *SortOrder
	Model *SortOrder
	Endpoint *SortOrder
	IsActive *SortOrder
	CreatedAt *SortOrder
	UpdatedAt *SortOrder
}

// EmbeddingConfigCreateInput holds data for creating a new EmbeddingConfig record.
type EmbeddingConfigCreateInput struct {
	Provider string
	ApiKey string
	Model *string
	Endpoint *string
	IsActive *bool
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

// EmbeddingConfigUpdateInput holds data for updating an existing EmbeddingConfig record.
type EmbeddingConfigUpdateInput struct {
	Provider *string
	ApiKey *string
	Model *string
	Endpoint *string
	IsActive *bool
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

// EmbeddingConfigFindManyArgs provides ORM-style args for FindMany queries on EmbeddingConfig.
type EmbeddingConfigFindManyArgs struct {
	Where   *EmbeddingConfigWhereInput
	OrderBy *EmbeddingConfigOrderByInput
	Take    *int
	Skip    *int
	Select  []string
}

// EmbeddingConfigFindFirstArgs provides ORM-style args for FindFirst queries on EmbeddingConfig.
type EmbeddingConfigFindFirstArgs struct {
	Where   *EmbeddingConfigWhereInput
	OrderBy *EmbeddingConfigOrderByInput
	Select  []string
}

// EmbeddingConfigFindUniqueArgs provides ORM-style args for FindUnique queries on EmbeddingConfig.
type EmbeddingConfigFindUniqueArgs struct {
	Where *EmbeddingConfigWhereInput
}

// EmbeddingConfigDeleteManyArgs provides ORM-style args for DeleteMany queries on EmbeddingConfig.
type EmbeddingConfigDeleteManyArgs struct {
	Where *EmbeddingConfigWhereInput
}

// EmbeddingConfigCountArgs provides ORM-style args for Count queries on EmbeddingConfig.
type EmbeddingConfigCountArgs struct {
	Where *EmbeddingConfigWhereInput
}

