// Code generated by an5ORM. DO NOT EDIT.
package an5client

import (
	"time"
)

// LlmConfig - LLM provider configuration. Stores API keys and model settings for AI features.
type LlmConfig struct {
	Id string `json:"id" db:"id"`
	Provider string `json:"provider" db:"provider"`
	ApiKey string `json:"apiKey" db:"api_key"`
	Model *string `json:"model,omitempty" db:"model"`
	Endpoint *string `json:"endpoint,omitempty" db:"endpoint"`
	IsActive bool `json:"isActive" db:"is_active"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
	UpdatedAt time.Time `json:"updatedAt" db:"updated_at"`
}

// ─── LlmConfig ORM Types ──────────────────────────────────────────────────────────

// LlmConfigWhereInput provides type-safe filtering for LlmConfig queries.
type LlmConfigWhereInput struct {
	AND []LlmConfigWhereInput
	OR  []LlmConfigWhereInput
	NOT *LlmConfigWhereInput
	Id *StringFilter
	Provider *StringFilter
	ApiKey *StringFilter
	Model *StringFilter
	Endpoint *StringFilter
	IsActive *BoolFilter
	CreatedAt *DateTimeFilter
	UpdatedAt *DateTimeFilter
}

// LlmConfigOrderByInput provides type-safe ordering for LlmConfig queries.
type LlmConfigOrderByInput struct {
	Id *SortOrder
	Provider *SortOrder
	ApiKey *SortOrder
	Model *SortOrder
	Endpoint *SortOrder
	IsActive *SortOrder
	CreatedAt *SortOrder
	UpdatedAt *SortOrder
}

// LlmConfigCreateInput holds data for creating a new LlmConfig record.
type LlmConfigCreateInput struct {
	Provider string
	ApiKey string
	Model *string
	Endpoint *string
	IsActive *bool
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

// LlmConfigUpdateInput holds data for updating an existing LlmConfig record.
type LlmConfigUpdateInput struct {
	Provider *string
	ApiKey *string
	Model *string
	Endpoint *string
	IsActive *bool
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

// LlmConfigFindManyArgs provides ORM-style args for FindMany queries on LlmConfig.
type LlmConfigFindManyArgs struct {
	Where   *LlmConfigWhereInput
	OrderBy *LlmConfigOrderByInput
	Take    *int
	Skip    *int
	Select  []string
}

// LlmConfigFindFirstArgs provides ORM-style args for FindFirst queries on LlmConfig.
type LlmConfigFindFirstArgs struct {
	Where   *LlmConfigWhereInput
	OrderBy *LlmConfigOrderByInput
	Select  []string
}

// LlmConfigFindUniqueArgs provides ORM-style args for FindUnique queries on LlmConfig.
type LlmConfigFindUniqueArgs struct {
	Where *LlmConfigWhereInput
}

// LlmConfigDeleteManyArgs provides ORM-style args for DeleteMany queries on LlmConfig.
type LlmConfigDeleteManyArgs struct {
	Where *LlmConfigWhereInput
}

// LlmConfigCountArgs provides ORM-style args for Count queries on LlmConfig.
type LlmConfigCountArgs struct {
	Where *LlmConfigWhereInput
}

