// Code generated by an5ORM. DO NOT EDIT.
package an5client

// ModelToTable maps model name variations to fully-qualified SQL table names.
var ModelToTable = map[string]string{
	"EmbeddingConfig": "[dbo].[embeddingconfigs]",
	"embeddingConfig": "[dbo].[embeddingconfigs]",
	"EmbeddingConfigs": "[dbo].[embeddingconfigs]",
	"embeddingConfigs": "[dbo].[embeddingconfigs]",
	"LlmConfig": "[dbo].[llmconfigs]",
	"llmConfig": "[dbo].[llmconfigs]",
	"LlmConfigs": "[dbo].[llmconfigs]",
	"llmConfigs": "[dbo].[llmconfigs]",
	"User": "[dbo].[users]",
	"user": "[dbo].[users]",
	"Users": "[dbo].[users]",
	"users": "[dbo].[users]",
	"Order": "[dbo].[orders]",
	"order": "[dbo].[orders]",
	"Orders": "[dbo].[orders]",
	"orders": "[dbo].[orders]",
}

// ModelPrimaryKeys maps model names to their primary key column name.
var ModelPrimaryKeys = map[string]string{
	"EmbeddingConfig": "id",
	"embeddingConfig": "id",
	"EmbeddingConfigs": "id",
	"embeddingConfigs": "id",
	"LlmConfig": "id",
	"llmConfig": "id",
	"LlmConfigs": "id",
	"llmConfigs": "id",
	"User": "id",
	"user": "id",
	"Users": "id",
	"users": "id",
	"Order": "id",
	"order": "id",
	"Orders": "id",
	"orders": "id",
}
