// Code generated by an5ORM. DO NOT EDIT.
package an5client

import (
	"time"
)

// EmbeddingConfig - Embedding provider configuration. Stores API keys and model settings for RAG features.
type EmbeddingConfig struct {
	Id string `json:"id" db:"id"`
	Provider string `json:"provider" db:"provider"`
	ApiKey string `json:"apiKey" db:"api_key"`
	Model *string `json:"model,omitempty" db:"model"`
	Endpoint *string `json:"endpoint,omitempty" db:"endpoint"`
	IsActive bool `json:"isActive" db:"is_active"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
	UpdatedAt time.Time `json:"updatedAt" db:"updated_at"`
}

// LlmConfig - LLM provider configuration. Stores API keys and model settings for AI features.
type LlmConfig struct {
	Id string `json:"id" db:"id"`
	Provider string `json:"provider" db:"provider"`
	ApiKey string `json:"apiKey" db:"api_key"`
	Model *string `json:"model,omitempty" db:"model"`
	Endpoint *string `json:"endpoint,omitempty" db:"endpoint"`
	IsActive bool `json:"isActive" db:"is_active"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
	UpdatedAt time.Time `json:"updatedAt" db:"updated_at"`
}

// User - Represents a registered user in the database.
type User struct {
	Id string `json:"id" db:"id"`
	Email string `json:"email" db:"email"`
	Name *string `json:"name,omitempty" db:"name"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
}

// Order - Represents a customer order in the system.
type Order struct {
	Id string `json:"id" db:"id"`
	UserId string `json:"userId" db:"user_id"`
	Total string `json:"total" db:"total"`
	CreatedAt time.Time `json:"createdAt" db:"created_at"`
}

