export * from './base';
export * from './EmbeddingConfig';
export * from './LlmConfig';
export * from './User';
export * from './Order';
import { An5 as BaseAn5 } from './base';
import * as EmbeddingConfigTypes from './EmbeddingConfig';
import * as LlmConfigTypes from './LlmConfig';
import * as UserTypes from './User';
import * as OrderTypes from './Order';
export declare namespace An5 {
    type SortOrder = BaseAn5.SortOrder;
    type StringFilter = BaseAn5.StringFilter;
    type StringNullableFilter = BaseAn5.StringNullableFilter;
    type NumberFilter = BaseAn5.NumberFilter;
    type NumberNullableFilter = BaseAn5.NumberNullableFilter;
    type BooleanFilter = BaseAn5.BooleanFilter;
    type BooleanNullableFilter = BaseAn5.BooleanNullableFilter;
    type DateTimeFilter = BaseAn5.DateTimeFilter;
    type DateTimeNullableFilter = BaseAn5.DateTimeNullableFilter;
    type IntFieldUpdateOperationsInput = BaseAn5.IntFieldUpdateOperationsInput;
    type FloatFieldUpdateOperationsInput = BaseAn5.FloatFieldUpdateOperationsInput;
    const An5ClientKnownRequestError: typeof import("@an5/orm").An5ClientKnownRequestError;
    type EmbeddingConfig = EmbeddingConfigTypes.EmbeddingConfig;
    type EmbeddingConfigWhereInput = EmbeddingConfigTypes.EmbeddingConfigWhereInput;
    type EmbeddingConfigSelect = EmbeddingConfigTypes.EmbeddingConfigSelect;
    type EmbeddingConfigInclude = EmbeddingConfigTypes.EmbeddingConfigInclude;
    type EmbeddingConfigCreateInput = EmbeddingConfigTypes.EmbeddingConfigCreateInput;
    type EmbeddingConfigUpdateInput = EmbeddingConfigTypes.EmbeddingConfigUpdateInput;
    type EmbeddingConfigOrderByInput = EmbeddingConfigTypes.EmbeddingConfigOrderByInput;
    type EmbeddingConfigFindManyArgs = EmbeddingConfigTypes.EmbeddingConfigFindManyArgs;
    type EmbeddingConfigFindFirstArgs = EmbeddingConfigTypes.EmbeddingConfigFindFirstArgs;
    type EmbeddingConfigFindUniqueArgs = EmbeddingConfigTypes.EmbeddingConfigFindUniqueArgs;
    type EmbeddingConfigCreateArgs = EmbeddingConfigTypes.EmbeddingConfigCreateArgs;
    type EmbeddingConfigUpdateArgs = EmbeddingConfigTypes.EmbeddingConfigUpdateArgs;
    type EmbeddingConfigUpsertArgs = EmbeddingConfigTypes.EmbeddingConfigUpsertArgs;
    type EmbeddingConfigDeleteArgs = EmbeddingConfigTypes.EmbeddingConfigDeleteArgs;
    type EmbeddingConfigTableClient = EmbeddingConfigTypes.EmbeddingConfigTableClient;
    type EmbeddingConfigScalarFieldEnum = EmbeddingConfigTypes.EmbeddingConfigScalarFieldEnum;
    type EmbeddingConfigAggregateArgs = EmbeddingConfigTypes.EmbeddingConfigAggregateArgs;
    type EmbeddingConfigGroupByArgs = EmbeddingConfigTypes.EmbeddingConfigGroupByArgs;
    type LlmConfig = LlmConfigTypes.LlmConfig;
    type LlmConfigWhereInput = LlmConfigTypes.LlmConfigWhereInput;
    type LlmConfigSelect = LlmConfigTypes.LlmConfigSelect;
    type LlmConfigInclude = LlmConfigTypes.LlmConfigInclude;
    type LlmConfigCreateInput = LlmConfigTypes.LlmConfigCreateInput;
    type LlmConfigUpdateInput = LlmConfigTypes.LlmConfigUpdateInput;
    type LlmConfigOrderByInput = LlmConfigTypes.LlmConfigOrderByInput;
    type LlmConfigFindManyArgs = LlmConfigTypes.LlmConfigFindManyArgs;
    type LlmConfigFindFirstArgs = LlmConfigTypes.LlmConfigFindFirstArgs;
    type LlmConfigFindUniqueArgs = LlmConfigTypes.LlmConfigFindUniqueArgs;
    type LlmConfigCreateArgs = LlmConfigTypes.LlmConfigCreateArgs;
    type LlmConfigUpdateArgs = LlmConfigTypes.LlmConfigUpdateArgs;
    type LlmConfigUpsertArgs = LlmConfigTypes.LlmConfigUpsertArgs;
    type LlmConfigDeleteArgs = LlmConfigTypes.LlmConfigDeleteArgs;
    type LlmConfigTableClient = LlmConfigTypes.LlmConfigTableClient;
    type LlmConfigScalarFieldEnum = LlmConfigTypes.LlmConfigScalarFieldEnum;
    type LlmConfigAggregateArgs = LlmConfigTypes.LlmConfigAggregateArgs;
    type LlmConfigGroupByArgs = LlmConfigTypes.LlmConfigGroupByArgs;
    type User = UserTypes.User;
    type UserWhereInput = UserTypes.UserWhereInput;
    type UserSelect = UserTypes.UserSelect;
    type UserInclude = UserTypes.UserInclude;
    type UserCreateInput = UserTypes.UserCreateInput;
    type UserUpdateInput = UserTypes.UserUpdateInput;
    type UserOrderByInput = UserTypes.UserOrderByInput;
    type UserFindManyArgs = UserTypes.UserFindManyArgs;
    type UserFindFirstArgs = UserTypes.UserFindFirstArgs;
    type UserFindUniqueArgs = UserTypes.UserFindUniqueArgs;
    type UserCreateArgs = UserTypes.UserCreateArgs;
    type UserUpdateArgs = UserTypes.UserUpdateArgs;
    type UserUpsertArgs = UserTypes.UserUpsertArgs;
    type UserDeleteArgs = UserTypes.UserDeleteArgs;
    type UserTableClient = UserTypes.UserTableClient;
    type UserScalarFieldEnum = UserTypes.UserScalarFieldEnum;
    type UserAggregateArgs = UserTypes.UserAggregateArgs;
    type UserGroupByArgs = UserTypes.UserGroupByArgs;
    type Order = OrderTypes.Order;
    type OrderWhereInput = OrderTypes.OrderWhereInput;
    type OrderSelect = OrderTypes.OrderSelect;
    type OrderInclude = OrderTypes.OrderInclude;
    type OrderCreateInput = OrderTypes.OrderCreateInput;
    type OrderUpdateInput = OrderTypes.OrderUpdateInput;
    type OrderOrderByInput = OrderTypes.OrderOrderByInput;
    type OrderFindManyArgs = OrderTypes.OrderFindManyArgs;
    type OrderFindFirstArgs = OrderTypes.OrderFindFirstArgs;
    type OrderFindUniqueArgs = OrderTypes.OrderFindUniqueArgs;
    type OrderCreateArgs = OrderTypes.OrderCreateArgs;
    type OrderUpdateArgs = OrderTypes.OrderUpdateArgs;
    type OrderUpsertArgs = OrderTypes.OrderUpsertArgs;
    type OrderDeleteArgs = OrderTypes.OrderDeleteArgs;
    type OrderTableClient = OrderTypes.OrderTableClient;
    type OrderScalarFieldEnum = OrderTypes.OrderScalarFieldEnum;
    type OrderAggregateArgs = OrderTypes.OrderAggregateArgs;
    type OrderGroupByArgs = OrderTypes.OrderGroupByArgs;
}
export declare class An5Client {
    $connect(): Promise<void>;
    $disconnect(): Promise<void>;
    $transaction<R>(fn: (tx: An5Client) => Promise<R>, options?: {
        timeout?: number;
    }): Promise<R>;
    $transaction<R>(list: Promise<R>[]): Promise<R[]>;
    $begin(): Promise<An5Client>;
    $commit(): Promise<void>;
    $rollback(): Promise<void>;
    $queryRaw<T = any>(queryParts: TemplateStringsArray | string, ...values: any[]): Promise<T>;
    $queryRawUnsafe<R = any>(query: string, ...values: any[]): Promise<R>;
    $executeRaw<T = any>(queryParts: TemplateStringsArray | string, ...values: any[]): Promise<any>;
    $executeRawUnsafe(query: string, ...values: any[]): Promise<number>;
    EmbeddingConfig: EmbeddingConfigTypes.EmbeddingConfigTableClient;
    embeddingConfig: EmbeddingConfigTypes.EmbeddingConfigTableClient;
    EmbeddingConfigs: EmbeddingConfigTypes.EmbeddingConfigTableClient;
    embeddingConfigs: EmbeddingConfigTypes.EmbeddingConfigTableClient;
    LlmConfig: LlmConfigTypes.LlmConfigTableClient;
    llmConfig: LlmConfigTypes.LlmConfigTableClient;
    LlmConfigs: LlmConfigTypes.LlmConfigTableClient;
    llmConfigs: LlmConfigTypes.LlmConfigTableClient;
    User: UserTypes.UserTableClient;
    user: UserTypes.UserTableClient;
    Users: UserTypes.UserTableClient;
    users: UserTypes.UserTableClient;
    Order: OrderTypes.OrderTableClient;
    order: OrderTypes.OrderTableClient;
    Orders: OrderTypes.OrderTableClient;
    orders: OrderTypes.OrderTableClient;
}
