//! Shared filter types for AN5 Rust client.
//! Code generated by an5ORM. DO NOT EDIT.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Sort direction.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "UPPERCASE")]
pub enum SortOrder {
    Asc,
    Desc,
}

impl SortOrder {
    pub fn as_sql(&self) -> &'static str {
        match self {
            SortOrder::Asc => "ASC",
            SortOrder::Desc => "DESC",
        }
    }
}

/// Database dialect for identifier quoting / placeholders.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Dialect {
    Mssql,
    Postgres,
    Sqlite,
}

impl Dialect {
    pub fn detect(conn_str: &str) -> Self {
        let l = conn_str.trim().to_lowercase();
        if l.starts_with("postgres://")
            || l.starts_with("postgresql://")
            || l.contains("port=5432")
        {
            return Dialect::Postgres;
        }
        if l.starts_with("sqlite://")
            || l.starts_with("sqlite:")
            || l.starts_with("file:")
            || l.ends_with(".db")
            || l.ends_with(".sqlite")
            || l.ends_with(".sqlite3")
            || l == ":memory:"
        {
            return Dialect::Sqlite;
        }
        Dialect::Mssql
    }

    pub fn quote_ident(&self, name: &str) -> String {
        match self {
            Dialect::Postgres | Dialect::Sqlite => {
                format!("\"{}\"", name.replace('"', "\"\""))
            }
            Dialect::Mssql => format!("[{}]", name.replace(']', "]]")),
        }
    }

    pub fn placeholder(&self, n: usize) -> String {
        match self {
            Dialect::Postgres => format!("${}", n),
            _ => "?".to_string(),
        }
    }
}

/// A typed bind parameter produced by the query builders.
///
/// Values keep their Rust type so drivers can bind them natively (a Bool
/// must not become the string "true" when the column is an integer).
#[derive(Debug, Clone, PartialEq)]
pub enum BindValue {
    Text(String),
    Int(i64),
    Float(f64),
    Bool(bool),
    /// RFC 3339 timestamp.
    DateTime(String),
}

impl BindValue {
    /// Textual rendering, useful for logging or drivers that take strings.
    pub fn as_str(&self) -> String {
        match self {
            BindValue::Text(v) => v.clone(),
            BindValue::Int(v) => v.to_string(),
            BindValue::Float(v) => v.to_string(),
            BindValue::Bool(v) => v.to_string(),
            BindValue::DateTime(v) => v.clone(),
        }
    }
}

impl std::fmt::Display for BindValue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl From<&str> for BindValue {
    fn from(v: &str) -> Self {
        BindValue::Text(v.to_string())
    }
}

impl From<String> for BindValue {
    fn from(v: String) -> Self {
        BindValue::Text(v)
    }
}

impl From<i64> for BindValue {
    fn from(v: i64) -> Self {
        BindValue::Int(v)
    }
}

impl From<f64> for BindValue {
    fn from(v: f64) -> Self {
        BindValue::Float(v)
    }
}

impl From<bool> for BindValue {
    fn from(v: bool) -> Self {
        BindValue::Bool(v)
    }
}

/// Type-safe filter for string fields.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct StringFilter {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub equals: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub not: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub contains: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub starts_with: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ends_with: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gt: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gte: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lt: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lte: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub in_list: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub not_in: Vec<String>,
}

/// Type-safe filter for integer fields.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct IntFilter {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub equals: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub not: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gt: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gte: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lt: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lte: Option<i64>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub in_list: Vec<i64>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub not_in: Vec<i64>,
}

/// Type-safe filter for float / decimal fields.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NumberFilter {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub equals: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub not: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gt: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gte: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lt: Option<f64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lte: Option<f64>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub in_list: Vec<f64>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub not_in: Vec<f64>,
}

/// Type-safe filter for boolean fields.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct BoolFilter {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub equals: Option<bool>,
}

/// Type-safe filter for datetime fields.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct DateTimeFilter {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub equals: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub not: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gt: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub gte: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lt: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lte: Option<DateTime<Utc>>,
}

// ─── SQL fragment builders (shared) ─────────────────────────────────────────

pub(crate) fn push_string_filter(
    col: &str,
    f: &StringFilter,
    dialect: Dialect,
    args: &mut Vec<BindValue>,
    parts: &mut Vec<String>,
) {
    let ph = |args: &Vec<BindValue>| dialect.placeholder(args.len() + 1);
    if let Some(v) = &f.equals {
        args.push(BindValue::Text(v.clone()));
        parts.push(format!("{} = {}", col, ph(args)));
    }
    if let Some(v) = &f.not {
        args.push(BindValue::Text(v.clone()));
        parts.push(format!("{} <> {}", col, ph(args)));
    }
    if let Some(v) = &f.contains {
        args.push(BindValue::Text(format!("%{}%", v)));
        parts.push(format!("{} LIKE {}", col, ph(args)));
    }
    if let Some(v) = &f.starts_with {
        args.push(BindValue::Text(format!("{}%", v)));
        parts.push(format!("{} LIKE {}", col, ph(args)));
    }
    if let Some(v) = &f.ends_with {
        args.push(BindValue::Text(format!("%{}", v)));
        parts.push(format!("{} LIKE {}", col, ph(args)));
    }
    if let Some(v) = &f.gt {
        args.push(BindValue::Text(v.clone()));
        parts.push(format!("{} > {}", col, ph(args)));
    }
    if let Some(v) = &f.gte {
        args.push(BindValue::Text(v.clone()));
        parts.push(format!("{} >= {}", col, ph(args)));
    }
    if let Some(v) = &f.lt {
        args.push(BindValue::Text(v.clone()));
        parts.push(format!("{} < {}", col, ph(args)));
    }
    if let Some(v) = &f.lte {
        args.push(BindValue::Text(v.clone()));
        parts.push(format!("{} <= {}", col, ph(args)));
    }
    if !f.in_list.is_empty() {
        let mut phs = Vec::new();
        for v in &f.in_list {
            args.push(BindValue::Text(v.clone()));
            phs.push(ph(args));
        }
        parts.push(format!("{} IN ({})", col, phs.join(", ")));
    }
    if !f.not_in.is_empty() {
        let mut phs = Vec::new();
        for v in &f.not_in {
            args.push(BindValue::Text(v.clone()));
            phs.push(ph(args));
        }
        parts.push(format!("{} NOT IN ({})", col, phs.join(", ")));
    }
}

pub(crate) fn push_int_filter(
    col: &str,
    f: &IntFilter,
    dialect: Dialect,
    args: &mut Vec<BindValue>,
    parts: &mut Vec<String>,
) {
    let ph = |args: &Vec<BindValue>| dialect.placeholder(args.len() + 1);
    if let Some(v) = f.equals {
        args.push(BindValue::Int(v));
        parts.push(format!("{} = {}", col, ph(args)));
    }
    if let Some(v) = f.not {
        args.push(BindValue::Int(v));
        parts.push(format!("{} <> {}", col, ph(args)));
    }
    if let Some(v) = f.gt {
        args.push(BindValue::Int(v));
        parts.push(format!("{} > {}", col, ph(args)));
    }
    if let Some(v) = f.gte {
        args.push(BindValue::Int(v));
        parts.push(format!("{} >= {}", col, ph(args)));
    }
    if let Some(v) = f.lt {
        args.push(BindValue::Int(v));
        parts.push(format!("{} < {}", col, ph(args)));
    }
    if let Some(v) = f.lte {
        args.push(BindValue::Int(v));
        parts.push(format!("{} <= {}", col, ph(args)));
    }
    if !f.in_list.is_empty() {
        let mut phs = Vec::new();
        for v in &f.in_list {
            args.push(BindValue::Int(*v));
            phs.push(ph(args));
        }
        parts.push(format!("{} IN ({})", col, phs.join(", ")));
    }
}

pub(crate) fn push_number_filter(
    col: &str,
    f: &NumberFilter,
    dialect: Dialect,
    args: &mut Vec<BindValue>,
    parts: &mut Vec<String>,
) {
    let ph = |args: &Vec<BindValue>| dialect.placeholder(args.len() + 1);
    if let Some(v) = f.equals {
        args.push(BindValue::Float(v));
        parts.push(format!("{} = {}", col, ph(args)));
    }
    if let Some(v) = f.not {
        args.push(BindValue::Float(v));
        parts.push(format!("{} <> {}", col, ph(args)));
    }
    if let Some(v) = f.gt {
        args.push(BindValue::Float(v));
        parts.push(format!("{} > {}", col, ph(args)));
    }
    if let Some(v) = f.gte {
        args.push(BindValue::Float(v));
        parts.push(format!("{} >= {}", col, ph(args)));
    }
    if let Some(v) = f.lt {
        args.push(BindValue::Float(v));
        parts.push(format!("{} < {}", col, ph(args)));
    }
    if let Some(v) = f.lte {
        args.push(BindValue::Float(v));
        parts.push(format!("{} <= {}", col, ph(args)));
    }
    if !f.in_list.is_empty() {
        let mut phs = Vec::new();
        for v in &f.in_list {
            args.push(BindValue::Float(*v));
            phs.push(ph(args));
        }
        parts.push(format!("{} IN ({})", col, phs.join(", ")));
    }
}

pub(crate) fn push_datetime_filter(
    col: &str,
    f: &DateTimeFilter,
    dialect: Dialect,
    args: &mut Vec<BindValue>,
    parts: &mut Vec<String>,
) {
    let ph = |args: &Vec<BindValue>| dialect.placeholder(args.len() + 1);
    if let Some(v) = &f.equals {
        args.push(BindValue::DateTime(v.to_rfc3339()));
        parts.push(format!("{} = {}", col, ph(args)));
    }
    if let Some(v) = &f.not {
        args.push(BindValue::DateTime(v.to_rfc3339()));
        parts.push(format!("{} <> {}", col, ph(args)));
    }
    if let Some(v) = &f.gt {
        args.push(BindValue::DateTime(v.to_rfc3339()));
        parts.push(format!("{} > {}", col, ph(args)));
    }
    if let Some(v) = &f.gte {
        args.push(BindValue::DateTime(v.to_rfc3339()));
        parts.push(format!("{} >= {}", col, ph(args)));
    }
    if let Some(v) = &f.lt {
        args.push(BindValue::DateTime(v.to_rfc3339()));
        parts.push(format!("{} < {}", col, ph(args)));
    }
    if let Some(v) = &f.lte {
        args.push(BindValue::DateTime(v.to_rfc3339()));
        parts.push(format!("{} <= {}", col, ph(args)));
    }
}


