//! Model → table mapping.
//! Code generated by an5ORM. DO NOT EDIT.

/// Resolve a model alias (User, user, users, …) to `schema.table`.
pub fn model_to_table(model: &str) -> Option<&'static str> {
    match model {
        "EmbeddingConfig" => Some("[dbo].[embeddingconfigs]"),
        "embeddingConfig" => Some("[dbo].[embeddingconfigs]"),
        "EmbeddingConfigs" => Some("[dbo].[embeddingconfigs]"),
        "embeddingConfigs" => Some("[dbo].[embeddingconfigs]"),
        "embedding_config" => Some("[dbo].[embeddingconfigs]"),
        "embedding_configs" => Some("[dbo].[embeddingconfigs]"),
        "LlmConfig" => Some("[dbo].[llmconfigs]"),
        "llmConfig" => Some("[dbo].[llmconfigs]"),
        "LlmConfigs" => Some("[dbo].[llmconfigs]"),
        "llmConfigs" => Some("[dbo].[llmconfigs]"),
        "llm_config" => Some("[dbo].[llmconfigs]"),
        "llm_configs" => Some("[dbo].[llmconfigs]"),
        "User" => Some("[dbo].[users]"),
        "user" => Some("[dbo].[users]"),
        "Users" => Some("[dbo].[users]"),
        "users" => Some("[dbo].[users]"),
        "Order" => Some("[dbo].[orders]"),
        "order" => Some("[dbo].[orders]"),
        "Orders" => Some("[dbo].[orders]"),
        "orders" => Some("[dbo].[orders]"),
        _ => None,
    }
}

/// Every model alias mapped to its physical table, for adapter registration.
pub fn model_to_table_map() -> Vec<(&'static str, &'static str)> {
    vec![
        ("EmbeddingConfig", "[dbo].[embeddingconfigs]"),
        ("embeddingConfig", "[dbo].[embeddingconfigs]"),
        ("EmbeddingConfigs", "[dbo].[embeddingconfigs]"),
        ("embeddingConfigs", "[dbo].[embeddingconfigs]"),
        ("embedding_config", "[dbo].[embeddingconfigs]"),
        ("embedding_configs", "[dbo].[embeddingconfigs]"),
        ("LlmConfig", "[dbo].[llmconfigs]"),
        ("llmConfig", "[dbo].[llmconfigs]"),
        ("LlmConfigs", "[dbo].[llmconfigs]"),
        ("llmConfigs", "[dbo].[llmconfigs]"),
        ("llm_config", "[dbo].[llmconfigs]"),
        ("llm_configs", "[dbo].[llmconfigs]"),
        ("User", "[dbo].[users]"),
        ("user", "[dbo].[users]"),
        ("Users", "[dbo].[users]"),
        ("users", "[dbo].[users]"),
        ("Order", "[dbo].[orders]"),
        ("order", "[dbo].[orders]"),
        ("Orders", "[dbo].[orders]"),
        ("orders", "[dbo].[orders]"),
    ]
}

/// Primary-key column (snake_case) for a model alias.
pub fn model_primary_key(model: &str) -> Option<&'static str> {
    match model {
        "EmbeddingConfig" => Some("id"),
        "embeddingConfig" => Some("id"),
        "EmbeddingConfigs" => Some("id"),
        "embeddingConfigs" => Some("id"),
        "embedding_config" => Some("id"),
        "embedding_configs" => Some("id"),
        "LlmConfig" => Some("id"),
        "llmConfig" => Some("id"),
        "LlmConfigs" => Some("id"),
        "llmConfigs" => Some("id"),
        "llm_config" => Some("id"),
        "llm_configs" => Some("id"),
        "User" => Some("id"),
        "user" => Some("id"),
        "Users" => Some("id"),
        "users" => Some("id"),
        "Order" => Some("id"),
        "order" => Some("id"),
        "Orders" => Some("id"),
        "orders" => Some("id"),
        _ => None,
    }
}
