//! Entity structs + typed Where / OrderBy / Args.
//! Code generated by an5ORM. DO NOT EDIT.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use crate::filters::*;

/// Embedding provider configuration. Stores API keys and model settings for RAG features.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbeddingConfig {
    /// Primary key
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Embedding provider: openai, cohere, custom
    pub provider: String,
    /// API key for the embedding service
    pub api_key: String,
    /// Model name, e.g. text-embedding-3-small
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// Custom endpoint URL
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    /// Whether this config is active
    #[serde(default, deserialize_with = "deserialize_option_bool_flexible", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// Creation timestamp
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
    /// Last update timestamp
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,
}

/// Type-safe WHERE filter for EmbeddingConfig queries.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbeddingConfigWhereInput {
    #[serde(default, rename = "AND", skip_serializing_if = "Option::is_none")]
    pub and: Option<Vec<EmbeddingConfigWhereInput>>,
    #[serde(default, rename = "OR", skip_serializing_if = "Option::is_none")]
    pub or: Option<Vec<EmbeddingConfigWhereInput>>,
    #[serde(default, rename = "NOT", skip_serializing_if = "Option::is_none")]
    pub not: Option<Box<EmbeddingConfigWhereInput>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<BoolFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTimeFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTimeFilter>,
}

/// Type-safe ORDER BY for EmbeddingConfig queries.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbeddingConfigOrderByInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<SortOrder>,
}

/// Typed data for creating a new EmbeddingConfig record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbeddingConfigCreateInput {
    pub provider: String,
    pub api_key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,
}

/// Typed data for updating an existing EmbeddingConfig record.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbeddingConfigUpdateInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,
}

/// ORM-style args for EmbeddingConfig.find_many().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbeddingConfigFindManyArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<EmbeddingConfigWhereInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_by: Option<EmbeddingConfigOrderByInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub take: Option<i64>,
    #[serde(default)]
    pub skip: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub select: Option<Vec<String>>,
}

/// ORM-style args for EmbeddingConfig.find_first().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbeddingConfigFindFirstArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<EmbeddingConfigWhereInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_by: Option<EmbeddingConfigOrderByInput>,
}

/// ORM-style args for EmbeddingConfig.find_unique() / count() / delete().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbeddingConfigFindUniqueArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<EmbeddingConfigWhereInput>,
}

/// ORM-style args for EmbeddingConfig.vector_search().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbeddingConfigVectorSearchArgs {
    pub vector: Vec<f32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub take: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<EmbeddingConfigWhereInput>,
    #[serde(default)]
    pub vector_field: String,
    #[serde(default)]
    pub distance_metric: String,
}

/// ORM-style args for EmbeddingConfig.update().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EmbeddingConfigUpdateArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<EmbeddingConfigWhereInput>,
    #[serde(default)]
    pub data: EmbeddingConfigUpdateInput,
}

/// LLM provider configuration. Stores API keys and model settings for AI features.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmConfig {
    /// Primary key
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// LLM provider: openai, gemini, custom, azure
    pub provider: String,
    /// API key for the LLM provider
    pub api_key: String,
    /// Model name, e.g. gpt-4o, gemini-2.5-flash
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// Custom endpoint URL
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    /// Whether this config is active
    #[serde(default, deserialize_with = "deserialize_option_bool_flexible", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// Creation timestamp
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
    /// Last update timestamp
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,
}

/// Type-safe WHERE filter for LlmConfig queries.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LlmConfigWhereInput {
    #[serde(default, rename = "AND", skip_serializing_if = "Option::is_none")]
    pub and: Option<Vec<LlmConfigWhereInput>>,
    #[serde(default, rename = "OR", skip_serializing_if = "Option::is_none")]
    pub or: Option<Vec<LlmConfigWhereInput>>,
    #[serde(default, rename = "NOT", skip_serializing_if = "Option::is_none")]
    pub not: Option<Box<LlmConfigWhereInput>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<BoolFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTimeFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTimeFilter>,
}

/// Type-safe ORDER BY for LlmConfig queries.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LlmConfigOrderByInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<SortOrder>,
}

/// Typed data for creating a new LlmConfig record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmConfigCreateInput {
    pub provider: String,
    pub api_key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,
}

/// Typed data for updating an existing LlmConfig record.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LlmConfigUpdateInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,
}

/// ORM-style args for LlmConfig.find_many().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LlmConfigFindManyArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<LlmConfigWhereInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_by: Option<LlmConfigOrderByInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub take: Option<i64>,
    #[serde(default)]
    pub skip: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub select: Option<Vec<String>>,
}

/// ORM-style args for LlmConfig.find_first().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LlmConfigFindFirstArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<LlmConfigWhereInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_by: Option<LlmConfigOrderByInput>,
}

/// ORM-style args for LlmConfig.find_unique() / count() / delete().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LlmConfigFindUniqueArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<LlmConfigWhereInput>,
}

/// ORM-style args for LlmConfig.vector_search().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LlmConfigVectorSearchArgs {
    pub vector: Vec<f32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub take: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<LlmConfigWhereInput>,
    #[serde(default)]
    pub vector_field: String,
    #[serde(default)]
    pub distance_metric: String,
}

/// ORM-style args for LlmConfig.update().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LlmConfigUpdateArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<LlmConfigWhereInput>,
    #[serde(default)]
    pub data: LlmConfigUpdateInput,
}

/// Represents a registered user in the database.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    /// Primary key for the User table (auto-generated UUID)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Unique email address used for login and notifications
    pub email: String,
    /// Display name of the user
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Timestamp when the user profile was created
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
}

/// Type-safe WHERE filter for User queries.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserWhereInput {
    #[serde(default, rename = "AND", skip_serializing_if = "Option::is_none")]
    pub and: Option<Vec<UserWhereInput>>,
    #[serde(default, rename = "OR", skip_serializing_if = "Option::is_none")]
    pub or: Option<Vec<UserWhereInput>>,
    #[serde(default, rename = "NOT", skip_serializing_if = "Option::is_none")]
    pub not: Option<Box<UserWhereInput>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTimeFilter>,
}

/// Type-safe ORDER BY for User queries.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserOrderByInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<SortOrder>,
}

/// Typed data for creating a new User record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserCreateInput {
    pub email: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
}

/// Typed data for updating an existing User record.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserUpdateInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
}

/// ORM-style args for User.find_many().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserFindManyArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<UserWhereInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_by: Option<UserOrderByInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub take: Option<i64>,
    #[serde(default)]
    pub skip: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub select: Option<Vec<String>>,
}

/// ORM-style args for User.find_first().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserFindFirstArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<UserWhereInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_by: Option<UserOrderByInput>,
}

/// ORM-style args for User.find_unique() / count() / delete().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserFindUniqueArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<UserWhereInput>,
}

/// ORM-style args for User.vector_search().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserVectorSearchArgs {
    pub vector: Vec<f32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub take: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<UserWhereInput>,
    #[serde(default)]
    pub vector_field: String,
    #[serde(default)]
    pub distance_metric: String,
}

/// ORM-style args for User.update().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UserUpdateArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<UserWhereInput>,
    #[serde(default)]
    pub data: UserUpdateInput,
}

/// Represents a customer order in the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    /// Primary key for the Order table (auto-generated UUID)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Foreign key linking to the User model who placed the order
    pub user_id: String,
    /// Total cost amount of the order
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// The date and time when the order was created.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
}

/// Type-safe WHERE filter for Order queries.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OrderWhereInput {
    #[serde(default, rename = "AND", skip_serializing_if = "Option::is_none")]
    pub and: Option<Vec<OrderWhereInput>>,
    #[serde(default, rename = "OR", skip_serializing_if = "Option::is_none")]
    pub or: Option<Vec<OrderWhereInput>>,
    #[serde(default, rename = "NOT", skip_serializing_if = "Option::is_none")]
    pub not: Option<Box<OrderWhereInput>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_id: Option<StringFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<IntFilter>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTimeFilter>,
}

/// Type-safe ORDER BY for Order queries.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OrderOrderByInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_id: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<SortOrder>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<SortOrder>,
}

/// Typed data for creating a new Order record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderCreateInput {
    pub user_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
}

/// Typed data for updating an existing Order record.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OrderUpdateInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,
}

/// ORM-style args for Order.find_many().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OrderFindManyArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<OrderWhereInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_by: Option<OrderOrderByInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub take: Option<i64>,
    #[serde(default)]
    pub skip: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub select: Option<Vec<String>>,
}

/// ORM-style args for Order.find_first().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OrderFindFirstArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<OrderWhereInput>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub order_by: Option<OrderOrderByInput>,
}

/// ORM-style args for Order.find_unique() / count() / delete().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OrderFindUniqueArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<OrderWhereInput>,
}

/// ORM-style args for Order.vector_search().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OrderVectorSearchArgs {
    pub vector: Vec<f32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub take: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<OrderWhereInput>,
    #[serde(default)]
    pub vector_field: String,
    #[serde(default)]
    pub distance_metric: String,
}

/// ORM-style args for Order.update().
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OrderUpdateArgs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub where_: Option<OrderWhereInput>,
    #[serde(default)]
    pub data: OrderUpdateInput,
}

